# Generated by Django 4.0.4 on 2022-06-06 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Béchar', 'Béchar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saïda', 'Saïda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdès', 'Boumerdès'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aïn Defla'), ('Naâma', 'Naâma'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Ghardaïa', 'Ghardaïa'), ('Relizane', 'Relizane'), ('Timimoun', 'Timimoun'), ('Bordj Badji Mokhtar', 'Bordj Badji Mokhtar'), ('Ouled Djellal', 'Ouled Djellal'), ('Béni Abbès', 'Béni Abbès'), ('In Salah', 'In Salah'), ('In Guezzam', 'In Guezzam'), ('Touggourt', 'Touggourt'), ('Djanet', 'Djanet'), ('El Meghaier', 'El Meghaier'), ('El Menia', 'El Menia')], max_length=50)),
                ('localisation', models.CharField(max_length=250)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_license', models.CharField(max_length=18, unique=True)),
                ('issued', models.DateField(verbose_name='Date')),
                ('type_license', models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('B', 'B'), ('C', 'C'), ('C1', 'C1'), ('D', 'D'), ('BE', 'BE'), ('CE', 'CE'), ('C1E', 'C1E'), ('DE', 'DE'), ('F', 'F')], max_length=3)),
                ('image_id', models.ImageField(null=True, upload_to='Documents\\imagesId')),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admin', 'admin'), ('secretary', 'secretary'), ('garage manager', 'garage manager')], max_length=20)),
                ('grade', models.CharField(choices=[('supervisor', 'supervisor'), ('officer', 'officer')], max_length=20)),
                ('ST', models.TimeField()),
                ('ET', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateField(verbose_name='Date')),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('type_user', models.CharField(choices=[('admin', 'admin'), ('renter', 'renter'), ('driver', 'driver'), ('owner', 'owner'), ('garage_manager', 'garage_manager'), ('secretary', 'secretary')], max_length=50)),
                ('user', models.OneToOneField(default='yes', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admin', 'admin'), ('secretary', 'secretary'), ('garage manager', 'garage manager')], max_length=20)),
                ('grade', models.CharField(choices=[('supervisor', 'supervisor'), ('officer', 'officer')], max_length=20)),
                ('Salary', models.CharField(choices=[('admin', 'admin'), ('secretary', 'secretary'), ('garage manager', 'garage manager')], max_length=20)),
            ],
            options={
                'unique_together': {('type', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'private'), ('business', 'business')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Date')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.driver')),
            ],
        ),
        migrations.CreateModel(
            name='garage_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcking.parcking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Entereprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterepriseName', models.CharField(blank=True, max_length=100, null=True)),
                ('commercialNum', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.renter')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.renter'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.useraccount'),
        ),
        migrations.AddField(
            model_name='driver',
            name='workWith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.entereprise'),
        ),
        migrations.CreateModel(
            name='blackList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=250)),
                ('add_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.renter')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.employee'),
        ),
    ]
