# Generated by Django 4.0.4 on 2022-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_useraccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='Salary',
            field=models.IntegerField(default=0),
        ),
    ]
