# Generated by Django 4.0.4 on 2022-06-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_salaries_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.driver'),
        ),
    ]
