# Generated by Django 3.2.13 on 2022-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_blacklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='activation_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='total_login_devices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='two_step_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_secret_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
