# Generated by Django 3.2.13 on 2022-06-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20220612_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='birthday',
        ),
    ]
