# Generated by Django 4.0.4 on 2022-06-06 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contart', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('promotion', models.IntegerField(default=0, null=True)),
                ('PDFBill', models.FileField(blank=True, upload_to='PDFs/Bills')),
                ('Contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contart.contrat')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
    ]
