# Generated by Django 4.0.4 on 2022-06-06 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('modele', models.CharField(choices=[('SUV', 'Sport Utility Vehicle'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Sports ', 'Sports '), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Wagon', 'Station Wagon'), ('Pickup ', 'Pickup Truck ')], max_length=50)),
                ('type', models.CharField(choices=[('car', 'car'), ('moto', 'motocycle'), ('bus', 'bus')], max_length=50)),
                ('buy_year', models.DateField()),
                ('gear_box', models.CharField(choices=[('m', 'manual'), ('a', 'automatic')], max_length=50)),
                ('nb_place', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (7, '7'), (12, '12'), (30, '30')])),
                ('couleur', models.CharField(max_length=50)),
                ('etat', models.CharField(choices=[('reserved', 'reserved'), ('available', 'available'), ('not available', 'not available'), ('broken', 'broken'), ('rented', 'rented'), ('new', 'new')], default='new', max_length=50)),
                ('mobilité_reduite', models.BooleanField()),
                ('moteur_type', models.CharField(choices=[('e', 'essence'), ('d', 'diesel'), ('h', 'hybride'), ('el', 'electric')], max_length=50)),
                ('priceH', models.IntegerField(default=0)),
                ('priceD', models.IntegerField(default=0)),
                ('spotLetter', models.CharField(blank=True, max_length=1)),
                ('spotNumber', models.IntegerField(blank=True)),
                ('photo', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='Documents/qr_codes')),
                ('parking', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parcking.parcking')),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('reserved', 'reserved'), ('available', 'available'), ('not available', 'not available'), ('broken', 'broken'), ('rented', 'rented'), ('new', 'new')], default='new', max_length=15)),
                ('parking', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parcking.parcking')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car', models.ManyToManyField(to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
