# Generated by Django 4.0.4 on 2022-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parcking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=250)),
                ('capacite', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('localisation', models.CharField(max_length=250)),
            ],
        ),
    ]
