# Generated by Django 4.0.4 on 2022-06-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('issue_location', models.CharField(choices=[('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Béchar', 'Béchar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saïda', 'Saïda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdès', 'Boumerdès'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aïn Defla'), ('Naâma', 'Naâma'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Ghardaïa', 'Ghardaïa'), ('Relizane', 'Relizane'), ('Timimoun', 'Timimoun'), ('Bordj Badji Mokhtar', 'Bordj Badji Mokhtar'), ('Ouled Djellal', 'Ouled Djellal'), ('Béni Abbès', 'Béni Abbès'), ('In Salah', 'In Salah'), ('In Guezzam', 'In Guezzam'), ('Touggourt', 'Touggourt'), ('Djanet', 'Djanet'), ('El Meghaier', 'El Meghaier'), ('El Menia', 'El Menia')], max_length=50)),
                ('return_location', models.CharField(choices=[('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Béchar', 'Béchar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saïda', 'Saïda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdès', 'Boumerdès'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aïn Defla'), ('Naâma', 'Naâma'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Ghardaïa', 'Ghardaïa'), ('Relizane', 'Relizane'), ('Timimoun', 'Timimoun'), ('Bordj Badji Mokhtar', 'Bordj Badji Mokhtar'), ('Ouled Djellal', 'Ouled Djellal'), ('Béni Abbès', 'Béni Abbès'), ('In Salah', 'In Salah'), ('In Guezzam', 'In Guezzam'), ('Touggourt', 'Touggourt'), ('Djanet', 'Djanet'), ('El Meghaier', 'El Meghaier'), ('El Menia', 'El Menia')], max_length=50)),
                ('state', models.CharField(choices=[('not payed', 'not payed'), ('driver not yet signed', 'driver not yet signed'), ('completed', 'completed'), ('active', 'active'), ('expired', 'expired')], max_length=25)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.driver')),
                ('Renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.renter')),
                ('car_rented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('enter_checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enter_checker', to='administration.garage_manager')),
                ('sort_checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sort_checker', to='administration.garage_manager')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.tool')),
            ],
        ),
    ]
