# Generated by Django 4.0.4 on 2022-06-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tool_rented',
            field=models.ManyToManyField(null=True, to='cars.tool'),
        ),
        migrations.DeleteModel(
            name='ReservationTool',
        ),
    ]
