# Generated by Django 4.0.4 on 2022-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('reservation', '0002_reservation_tool_rented_delete_reservationtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tool_rented',
            field=models.ManyToManyField(blank=True, null=True, to='cars.tool'),
        ),
    ]
