# Generated by Django 4.0.4 on 2022-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('reservation', '0003_alter_reservation_tool_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tool_rented',
            field=models.ManyToManyField(blank=True, to='cars.tool'),
        ),
    ]
