# Generated by Django 4.0.4 on 2022-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_tool_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('not payed', 'not payed'), ('not completed', 'not completed'), ('driver not yet signed', 'driver not yet signed'), ('completed', 'completed'), ('active', 'active'), ('expired', 'expired')], max_length=25),
        ),
    ]
