# Generated by Django 4.0.4 on 2022-06-06 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('signatureDriver', models.ImageField(null=True, upload_to='PDFs/signatures')),
                ('signatureRenter', models.ImageField(null=True, upload_to='PDFs/signatures')),
                ('PDFFile', models.FileField(blank=True, upload_to='PDFs/Contracts')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
                ('secretary_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.secretary')),
            ],
        ),
    ]
