# Generated by Django 4.0.4 on 2022-06-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contart', '0002_contrat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='signatureDriver',
            field=models.ImageField(blank=True, null=True, upload_to='PDFs/signatures'),
        ),
    ]
