# Generated by Django 4.0.4 on 2022-06-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contart', '0003_alter_contrat_signaturedriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='signatureRenter',
            field=models.ImageField(blank=True, null=True, upload_to='PDFs/signatures'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type',
            field=models.CharField(choices=[('new', 'new'), ('renew', 'renew')], default='new', max_length=50),
        ),
    ]
